#ifndef FLB_OUT_FILE
#define FLB_OUT_FILE

enum {
    FLB_OUT_FILE_FMT_JSON,
    FLB_OUT_FILE_FMT_CSV,
    FLB_OUT_FILE_FMT_LTSV,
    FLB_OUT_FILE_FMT_PLAIN,
    FLB_OUT_FILE_FMT_MSGPACK,
    FLB_OUT_FILE_FMT_TEMPLATE,
};

#endif
